from discord.ext import commands


class AutoCompleteCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        '''Loaded Autocomplete'''

    def bot_command_list(self):
        commands_list = self.bot.commands
        return commands_list

    async def commands_list_autocomplete(self, interaction, value):
        return [x for x in self.bot_command_list() if x.startswith(value.lower())]

    async def language_autocomplete(self, interaction, value):
        return [x for x in GOOGLE_LANGUAGES if x.startswith(value.lower())]


def setup(bot):
    bot.add_cog(AutoCompleteCog(bot))


GOOGLE_LANGUAGES = ['afrikaans',
                    'albanian',
                    'amharic',
                    'arabic',
                    'armenian',
                    'azerbaijani',
                    'basque',
                    'belarusian',
                    'bengali',
                    'bosnian',
                    'bulgarian',
                    'catalan',
                    'cebuano',
                    'chichewa',
                    'chinese (simplified)',
                    'chinese (traditional)',
                    'corsican',
                    'croatian',
                    'czech',
                    'danish',
                    'dutch',
                    'english',
                    'esperanto',
                    'estonian',
                    'filipino',
                    'finnish',
                    'french',
                    'frisian',
                    'galician',
                    'georgian',
                    'german',
                    'greek',
                    'gujarati',
                    'haitian creole',
                    'hausa',
                    'hawaiian',
                    'hindi',
                    'hmong',
                    'hungarian',
                    'icelandic',
                    'igbo',
                    'indonesian',
                    'irish',
                    'italian',
                    'japanese',
                    'javanese',
                    'kannada',
                    'kazakh',
                    'khmer',
                    'korean',
                    'kurdish (kurmanji)',
                    'kyrgyz',
                    'lao',
                    'latin',
                    'latvian',
                    'lithuanian',
                    'luxembourgish',
                    'macedonian',
                    'malagasy',
                    'malay',
                    'malayalam',
                    'maltese',
                    'maori',
                    'marathi',
                    'mongolian',
                    'myanmar (burmese)',
                    'nepali',
                    'norwegian',
                    'pashto',
                    'persian',
                    'polish',
                    'portuguese',
                    'punjabi',
                    'romanian',
                    'russian',
                    'samoan',
                    'scots gaelic',
                    'serbian',
                    'sesotho',
                    'shona',
                    'sindhi',
                    'sinhala',
                    'slovak',
                    'slovenian',
                    'somali',
                    'spanish',
                    'sundanese',
                    'swahili',
                    'swedish',
                    'tajik',
                    'tamil',
                    'telugu',
                    'thai',
                    'turkish',
                    'ukrainian',
                    'urdu',
                    'uzbek',
                    'vietnamese',
                    'welsh',
                    'xhosa',
                    'yiddish',
                    'yoruba',
                    'zulu',
                    'Filipino',
                    'hebrew']

CSS_COLORS = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgrey",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "grey",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgrey",
    "lightgreen",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab"
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
]

image_filters = ["equations",
                 "print",
                 "glitch",
                 "blur",
                 "matrix",
                 "hearts",
                 "patpat",
                 "cartoon",
                 "earthquake"]
